<template>
  <main class="home">
    <MenuComponent />
    <section class="hero">
      <div class="hero-copy"><p class="eyebrow">TU GUÍA DE VIAJE CONFIABLE</p><h1>Descubre Santa Marta<br><em>con tranquilidad.</em></h1><p class="lead">Planes, recomendaciones y consejos útiles para disfrutar cada rincón de la Perla de América.</p><div class="actions"><router-link to="/mapview">Explorar lugares <b>→</b></router-link><a href="tel:123">☎ Línea de emergencias</a></div></div>
      <div class="hero-art" aria-hidden="true"><span class="sun">☀</span><span class="mountain">⛰</span><span class="palm">♣</span><i></i></div>
    </section>
    <section class="quick" id="seguridad"><div class="heading"><p class="eyebrow">TODO A LA MANO</p><h2>¿Qué necesitas hoy?</h2></div><div class="quick-grid"><router-link to="/mapview"><span>🗺️</span><strong>Explorar lugares</strong><small>Playas, cultura y naturaleza</small></router-link><a href="#consejos"><span>🛡️</span><strong>Viaja seguro</strong><small>Tips para tu recorrido</small></a><a class="urgent" href="tel:123"><span>🚨</span><strong>Emergencias</strong><small>Ten ayuda a un toque</small></a></div></section>
    <section class="tips" id="consejos"><div><p class="eyebrow">UN CONSEJO PARA HOY</p><h2>El mejor recuerdo es un viaje seguro.</h2></div><p>Guarda tus objetos de valor, usa transporte autorizado y consulta nuestra selección de lugares antes de salir.</p></section>
  </main>
</template>
<script>import MenuComponent from '../components/MenuComponent.vue'; export default { name: 'HomeView', components: { MenuComponent } }</script>
<style scoped>
.home { min-height: 100vh; font-family: Arial, Helvetica, sans-serif; color: #073b4c; }.hero { min-height: 480px; display: grid; grid-template-columns: 1.05fr .95fr; overflow: hidden; background: linear-gradient(115deg,#edf9f5 0 52%,#ccefe7 52%); }.hero-copy { max-width: 630px; padding: 88px 8% 70px; margin-left: auto; }.eyebrow { color: #118a7e; font-size: .72rem; font-weight: 800; letter-spacing: .15em; margin: 0 0 .7rem; } h1 { margin: 0; font-size: clamp(2.4rem,4.4vw,4.5rem); letter-spacing: -.06em; line-height: .98; } h1 em { color: #ef476f; font-style: normal; }.lead { max-width: 480px; color: #43606b; font-size: 1.05rem; line-height: 1.65; margin: 1.5rem 0 2rem; }.actions { display: flex; align-items: center; gap: 1.3rem; flex-wrap: wrap; }.actions a { color: #073b4c; font-weight: 700; text-decoration: none; }.actions a:first-child { padding: .9rem 1.25rem; border-radius: .7rem; background: #073b4c; color: white; box-shadow: 0 8px 18px #073b4c33; }.actions b { font-size: 1.3rem; }.hero-art { position: relative; min-height: 400px; overflow: hidden; background: linear-gradient(#b8e6e4 0 62%,#3caaa9 62% 70%,#0b7189 70%); }.sun { position: absolute; top: 13%; right: 22%; font-size: 5rem; color: #ffd166; }.mountain { position: absolute; bottom: 20%; left: 12%; font-size: 9rem; color: #247b7b; }.palm { position: absolute; bottom: 16%; right: 14%; font-size: 9rem; color: #075b61; transform: rotate(-25deg); }.hero-art i { position: absolute; bottom: 0; width: 100%; height: 30%; background: repeating-radial-gradient(ellipse,#44b9c0 0 3px,transparent 4px 17px); opacity: .65; }.quick { max-width: 1120px; margin: auto; padding: 70px 28px; }.heading { text-align: center; margin-bottom: 28px; }.heading h2,.tips h2 { margin: 0; font-size: 2rem; letter-spacing: -.03em; }.quick-grid { display: grid; grid-template-columns: repeat(3,1fr); gap: 20px; }.quick-grid a { min-height: 166px; display: flex; flex-direction: column; gap: .35rem; padding: 1.4rem; border: 1px solid #dcebea; border-radius: 16px; color: #073b4c; background: white; text-decoration: none; box-shadow: 0 8px 22px #073b4c0d; transition: transform .2s; }.quick-grid a:hover { transform: translateY(-4px); }.quick-grid span { font-size: 2rem; }.quick-grid strong { margin-top: .3rem; }.quick-grid small { color: #5e7780; }.quick-grid .urgent { background: #fff4f6; border-color: #ffd4dd; }.tips { max-width: 1064px; display: grid; grid-template-columns: 1fr 1fr; gap: 40px; align-items: center; margin: 0 auto 56px; padding: 32px 40px; border-radius: 18px; color: white; background: #118a7e; }.tips .eyebrow { color: #c7fff1; }.tips p:last-child { margin: 0; line-height: 1.65; color: #e8fffb; } @media(max-width:760px) { .hero,.quick-grid,.tips { grid-template-columns:1fr; }.hero { background:#edf9f5; }.hero-copy { padding:58px 7% 45px; }.hero-art { min-height:260px; }.tips { margin:0 18px 40px; padding:28px; gap:20px; } }
</style>
