<template>
  <main class="map-view"><MenuComponent /><section class="page-heading"><p>EXPLORA A TU RITMO</p><h1>Lugares para enamorarte<br>de Santa Marta</h1><span>Filtra los destinos y arma un plan memorable.</span></section><section class="places"><label class="search"><b>⌕</b><input v-model="busqueda" type="search" placeholder="Busca una playa, parque o zona..."></label><p class="counter">{{ lugaresFiltrados.length }} lugares recomendados</p><div class="places-grid"><article v-for="lugar in lugaresFiltrados" :key="lugar.name"><img :src="require(`../assets/${lugar.nameImage}`)" :alt="lugar.name"><div><small>{{ lugar.tipo }}</small><h2>{{ lugar.name }}</h2><p>{{ lugar.parragraf }}</p></div></article></div><p v-if="!lugaresFiltrados.length" class="empty">No encontramos lugares con ese nombre. Prueba otra búsqueda.</p></section></main>
</template>
<script>
import MenuComponent from '../components/MenuComponent.vue'
export default { name: 'MapView', components: { MenuComponent }, data: () => ({ busqueda: '', lugares: [{nameImage:'playa blanca.png',name:'Playa Blanca',tipo:'Playa',parragraf:'Ideal para descansar en pareja, a pocos minutos del centro.'},{nameImage:'parque tayrona.png',name:'Parque Tayrona',tipo:'Naturaleza',parragraf:'Naturaleza y senderismo. Lleva agua y protector solar.'},{nameImage:'centro historico.png',name:'Centro Histórico',tipo:'Cultura',parragraf:'Gastronomía típica y cultura samaria en un mismo recorrido.'}] }), computed: { lugaresFiltrados () { const f = this.busqueda.trim().toLowerCase(); return this.lugares.filter(l => `${l.name} ${l.tipo}`.toLowerCase().includes(f)) } } }
</script>
<style scoped>
.map-view { min-height:100vh; font-family:Arial,Helvetica,sans-serif; color:#073b4c; }.page-heading { padding:64px 7% 56px; text-align:center; color:#fff; background:linear-gradient(110deg,#073b4c,#118a7e); }.page-heading p { margin:0 0 .6rem; color:#b9fff1; font-size:.72rem; font-weight:800; letter-spacing:.15em; }.page-heading h1 { margin:0; font-size:clamp(2rem,4vw,3.5rem); letter-spacing:-.05em; line-height:1.05; }.page-heading span { display:block; margin-top:1rem; color:#e7fffb; }.places { max-width:1120px; margin:auto; padding:36px 28px 70px; }.search { max-width:620px; display:flex; align-items:center; gap:12px; padding:.85rem 1.1rem; margin:-68px auto 16px; border-radius:12px; background:white; box-shadow:0 10px 28px #073b4c29; }.search b { font-size:1.5rem; color:#118a7e; }.search input { width:100%; border:0; outline:0; color:#073b4c; font-size:1rem; }.counter { color:#62808a; font-size:.9rem; }.places-grid { display:grid; grid-template-columns:repeat(3,1fr); gap:22px; }.places-grid article { overflow:hidden; border-radius:16px; background:#fff; box-shadow:0 8px 24px #073b4c12; }.places-grid img { width:100%; height:210px; display:block; object-fit:cover; }.places-grid article div { padding:1.25rem; }.places-grid small { padding:.28rem .6rem; border-radius:99px; background:#dff6f0; color:#118a7e; font-weight:700; }.places-grid h2 { margin:.8rem 0 .45rem; font-size:1.3rem; }.places-grid p { margin:0; color:#5e7780; line-height:1.5; }.empty { padding:56px; text-align:center; color:#62808a; } @media(max-width:760px) { .places-grid { grid-template-columns:1fr; }.page-heading { padding:48px 8% 60px; }.places { padding-left:18px; padding-right:18px; } }
</style>
